services:
  resource-server:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./resource-server/resources:/usr/share/nginx/html:ro
      - ./resource-server/nginx.conf:/etc/nginx/nginx.conf:ro

  redis-cache:
    image: redis:7
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data

  react-sneakers-db:
    image: postgres:16
    environment:
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - react_sneakers_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  react-sneakers-api:
    build:
      context: ./react-sneakers-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - react-sneakers-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://react-sneakers-db:5432/${POSTGRES_DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_DATA_REDIS_HOST=6379
      - SPRING_DATA_REDIS_HOST=redis-cache
      - HOST_ADDRESS=${HOST_ADDRESS}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}

  react-sneakers-app:
    build:
      context: ./react-sneakers-app
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - node_modules:/app/node-modules
    depends_on:
      - react-sneakers-api

volumes:
  redis_data:
  react_sneakers_data:
  node_modules: