version: '3.8'

services:
  resource-server:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./resource-server/resources:/usr/share/nginx/html:ro
      - ./resource-server/nginx.conf:/etc/nginx/nginx.conf:ro
