spring:
  application:
    name: react-sneakers-api
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/react_sneakers_db
    username: postgres
    password: 1
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true