app:
  jwt:
    secret: MJR3#y#FEp}T90dh4)!:\d!|r?C$O+8TQr&vcI,lY@BPYJO*tayg1kEVd5ud#9R1
    subject: react-sneakers-api
    issuer: User details service
    expiration: 43200000 # 12 hours
    total-expiration: 1209600000 # 2 weeks
  host-address: ${HOST_ADDRESS}
  email-confirmation: false

spring:
  application:
    name: react-sneakers-api
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/react_sneakers_db
    username: postgres
    password: 1
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp:
        auth: true
        starttls.enable: true
logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: debug