DROP TABLE cart_item;

CREATE TABLE cart_item
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    sneaker_item_id int REFERENCES sneaker_item(id) ON DELETE CASCADE NOT NULL,
    user_id int REFERENCES users(id) ON DELETE CASCADE NOT NULL ,
    quantity int NOT NULL DEFAULT 1,
    UNIQUE (sneaker_item_id, user_id)
);