CREATE TABLE sneaker
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    name varchar(120) UNIQUE NOT NULL,
    image_url text,
    price decimal NOT NULL ,
    description varchar(512) NOT NULL ,
    firm_id int REFERENCES firm(id) NOT NULL
)