DROP TABLE orders CASCADE ;

CREATE TABLE orders
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    user_id int REFERENCES users(id) ON DELETE CASCADE ,
    status varchar(16) NOT NULL CHECK (status IN ('canceled', 'pending', 'completed')),
    created_at timestamp
)