DROP TABLE order_item;

CREATE TABLE  order_item
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    order_id int REFERENCES orders(id) ON DELETE CASCADE NOT NULL ,
    sneaker_item_id int REFERENCES sneaker_item(id) ON DELETE CASCADE NOT NULL ,
    quantity int NOT NULL DEFAULT 1,
    UNIQUE (order_id, sneaker_item_id)
);