INSERT INTO sneaker (name, image_url, price, description, firm_id) VALUES
('Nike Air Max 270', '/images/sneaker/nike-air-max-270.jpg', 150.00, 'Легкие кроссовки с максимальной амортизацией.', 1),
('Nike Air Force 1', '/images/sneaker/nike-air-force-1.jpg', 110.00, 'Классическая модель в белом цвете — икона уличной моды.', 1),
('Nike Dunk Low', '/images/sneaker/nike-dunk-low.jpg', 120.00, 'Низкий профиль, стиль и удобство.', 1),
('Adidas Crazy 8 Low', '/images/sneaker/adidas-crazy8-low.jpg', 180.00, 'Беговые кроссовки с Boost-подошвой.', 2),
('Adidas Samba OG', '/images/sneaker/adidas-samba-og.jpg', 100.00, 'Ретро силуэт с кожаным верхом.', 2),
('Adidas NMD R1', '/images/sneaker/nmd-r1.jpg', 140.00, 'Современный дизайн и комфорт.', 2),
('Puma RS-X', '/images/sneaker/puma-rs-x.jpg', 110.00, 'Ретро силуэт и массивный дизайн.', 3),
('Puma Suede Classic', '/images/sneaker/puma-suede-classic.webp', 75.00, 'Иконка стиля с 1968 года.', 3),
('Converse Chuck Taylor All Star', '/images/sneaker/converse-chunk-taylor-all-star.jpg', 60.00, 'Классические высокие кеды.', 4),
('Converse Run Star Hike', '/images/sneaker/converse-run-star-hike.png', 120.00, 'Массивная подошва и узнаваемый силуэт.', 4),
('Vans Old Skool', '/images/sneaker/vans-old-skool.jpeg', 70.00, 'Кеды с фирменной полоской.', 5),
('Vans Sk8-Hi', '/images/sneaker/vans-sk8-hi.jpg', 80.00, 'Высокие кеды для скейтбординга.', 5),
('New Balance 574', '/images/sneaker/new-balance-574.jpg', 90.00, 'Универсальные кроссовки в ретро-стиле.', 6),
('New Balance 327', '/images/sneaker/new-balance-327.jpg', 100.00, 'Модный силуэт с отсылкой к 70-м.', 6),
('Reebok Club C 85', '/images/sneaker/reebok-club-c85.jpeg', 85.00, 'Минимализм и комфорт.', 7),
('Reebok Classic Leather', '/images/sneaker/reebok-classic-leather.jpg', 80.00, 'Кожаные кроссовки в классическом стиле.', 7),
('ASICS Gel Kahana 8', '/images/sneaker/asics-gel-kahana8.jpg', 160.00, 'Поддержка и амортизация для бега.', 8),
('ASICS GEL-Lyte III', '/images/sneaker/asics-gel-lyte3.jpg', 120.00, 'Ретро-образ с расщеплённым язычком.', 8),
('Air Jordan 1 Mid', '/images/sneaker/air-jordan-1-mid.jpg', 130.00, 'Легендарные кроссовки от Майкла Джордана.', 9),
('Under Armour HOVR Phantom 3', '/images/sneaker/under-armour-hovr-phantom3.png', 140.00, 'Современные технологии для тренировок.', 10);
